version: '3.7'

services:
  ingress:
    build: ./
    image: jkolczasty/nginx-ingress-ctrl:0.9-alpine-20240403
    ports:
      - "80:80"
      - "443:443"
    environment:
      TIMEZONE: 'Europe/Warsaw'
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro

    networks:
      - myapp

networks:
  myapp:
    external: true
